# Generated by Django 2.1.4 on 2019-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, choices=[('1', '1-ка'), ('2', '2-ка'), ('3', '3-ка'), ('4', '4-ка'), ('5', 'Коммерческая недвижимость')], default='1', help_text='Выберите тип помещения', max_length=1)),
                ('address', models.CharField(help_text='Введите адрес', max_length=100)),
                ('telephone', models.FloatField(help_text='Введите телефон', unique=True)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('image1', models.ImageField(null=True, upload_to='premises/%Y/%m/%d')),
                ('image2', models.ImageField(null=True, upload_to='premises/%Y/%m/%d')),
                ('image3', models.ImageField(null=True, upload_to='premises/%Y/%m/%d')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['types', '-date'],
            },
        ),
    ]
