# Generated by Django 2.1.4 on 2019-03-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premises',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='premises',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='premises',
            name='image3',
        ),
    ]
