# Generated by Django 2.1.4 on 2019-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0003_auto_20190306_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='premises/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='premises/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='premises',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='premises/%Y/%m/%d'),
        ),
    ]
