# Generated by Django 2.1.4 on 2019-03-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0004_auto_20190314_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='premises/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='premises',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='premises',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='premises',
            name='image3',
        ),
        migrations.AddField(
            model_name='photo',
            name='premises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rieltor.Premises'),
        ),
    ]
