# Generated by Django 2.1.4 on 2019-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0005_auto_20190319_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='telephone',
            field=models.CharField(help_text='Введите телефон', max_length=100, unique=True),
        ),
    ]
