# Generated by Django 2.1.4 on 2019-04-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0009_premises_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
