# Generated by Django 2.1.4 on 2019-04-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0013_auto_20190405_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premises',
            options={'ordering': ['types', '-date'], 'permissions': (('can_see_premises', 'Возможность просматривать записи'), ('can_see_edit', 'Возможность редактировать записи'))},
        ),
    ]
