# Generated by Django 2.1.4 on 2019-04-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0014_auto_20190405_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premises',
            options={'ordering': ['types', '-date'], 'permissions': (('can_see_premises', 'Возможность просматривать записи'), ('can_change_premises', 'Возможность редактировать записи'))},
        ),
    ]
