# Generated by Django 2.1.4 on 2019-04-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0016_auto_20190405_0929'),
    ]

    operations = [
    ]
