# Generated by Django 2.1.4 on 2019-04-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0017_auto_20190405_0933'),
    ]

    operations = [
    ]
