# Generated by Django 2.1.4 on 2019-04-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0018_auto_20190405_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premises',
            options={'ordering': ['types', '-date'], 'permissions': (('can_see_premises', 'Возможность просматривать записи'), ('can_change_premises', 'Возможность редактировать записи'), ('can_delete_premises', 'Возможность удалять записи'), ('can_create_premises', 'Возможность создавать записи'))},
        ),
    ]
