# Generated by Django 2.1.4 on 2019-04-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0019_auto_20190405_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['premises'], 'permissions': (('can_see_premises', 'Возможность просматривать фотографии'), ('can_change_premises', 'Возможность редактировать фотографии'), ('can_delete_premises', 'Возможность удалять фотографии'), ('can_create_premises', 'Возможность создавать фотографии'))},
        ),
    ]
