# Generated by Django 2.1.4 on 2019-04-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rieltor', '0022_auto_20190405_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premises',
            options={'ordering': ['types', '-date'], 'permissions': (('can_see_premises', 'Возможность просматривать записи'), ('can_change_premises', 'Возможность редактировать записи'), ('can_delete_premises', 'Возможность удалять записи'), ('can_create_premises', 'Возможность создавать записи'), ('can_change_users', 'Возможность редактировать пользователя'), ('can_delete_users', 'Возможность удалять пользователя'), ('can_create_users', 'Возможность создавать пользователя'))},
        ),
    ]
